#+TITLE: Аутентификация пользователей CentOS 5/6 с использованием OpenLDAP 2.3/2.4
#+OPTIONS: toc:4 H:6 num:nil html-postamble:nil ^:nil tags:nil
#+SETUPFILE: theme-readtheorg-local.setup

В данном документе применяется управление конфигурациями при помощи [[https://www.docker.com/what-docker][Docker]]. Все документируемые команды и конфигурационные файлы прошли проверку на работоспособность в воспроизводимом программном окружении, которое доступно в проекте [[https://github.com/boykov/cc-ldap-centos][cc-ldap-centos]].

* Установка и настройка сервера OpenLDAP
:PROPERTIES:
:CUSTOM_ID: install-and-config
:ID:       f3a148ae-26f4-4c54-a25c-532d2b9086ba
:END:

#+begin_quote
Необходимо разработать документацию по установке и настройке сервера LDAP в ОС CentOS 5. Предпочтение отдавать реализациям, доступным в базовом репозитории дистрибутива. Проверить работоспособность выработанных инструкций в ОС CentOS 6.
#+end_quote

** OpenLDAP 2.3 и CentOS 5
:PROPERTIES:
:CUSTOM_ID: ldap2.3-centos5
:ID:       cdb77a09-a1eb-4db8-ad05-e45c3b49418c
:END:

# #+INCLUDE: "../ldap-server/Dockerfile" src dockerfile :lines "6-7"

В CentOS 5 из базового репозитория устанавливается 2.3 версия OpenLDAP.
# #+INCLUDE: "../ldap-server/Dockerfile" src dockerfile :lines "18-21"
# #+begin_tip
# Там, где это не вызывает недоразумений, иногда будет использоваться синтаксис Dockerfile. Например, предыдущая команда означает просто src_sh[:exports code]{yum -y install openldap-server openldap-clients}.
# #+end_tip
#+begin_src sh
yum -y install openldap-server openldap-clients
#+end_src
#+name: run-prefix
#+begin_src sh :exports none
#!/bin/bash

# for testing purpose
LDAP_ROOT_PASSWORD=root
LDAP_MANAGER_PASSWORD=manager

set -e

if [ ! -f /data/lib/ldap/DB_CONFIG ]; then
    if [ -z "$LDAP_ROOT_PASSWORD" -o -z "$LDAP_MANAGER_PASSWORD" ]; then
	echo "Need LDAP_ROOT_PASSWORD and LDAP_MANAGER_PASSWORD"
	exit
    fi

#+end_src
Для запуска сервиса src_sh[:exports code]{ldap} необходимо подготовить каталог и файл конфигурации базы данных.
#+name: run-db-config
#+begin_src sh :exports none
    cp /etc/openldap/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
    chown ldap. /var/lib/ldap/DB_CONFIG

#+end_src
#+begin_src sh :exports code :noweb yes
<<run-db-config>>
#+end_src

#+name: run-slapd-conf
#+begin_src sh :exports none
    rm -f /etc/openldap/slapd.conf
    cp /root/slapd.conf /etc/openldap/slapd.conf
    chown ldap. /etc/openldap/slapd.conf

    service ldap start
    sleep 3

#+end_src
#+begin_src sh :exports code :noweb yes
<<run-slapd-conf>>
#+end_src

#+begin_html
<a href="javascript:toggleDiv('myContent');" class="fa">slapd.conf</a>
#+end_html

#+HTML: <div id="myContent" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-server/slapd.conf src conf-space
#+HTML: </div>

#+name: run-slapd-d
#+begin_src sh :exports none
    killall slapd
    oldpath=`pwd`
    cd /etc/openldap
    mkdir slapd.d
    slaptest -f slapd.conf -F slapd.d
    chown -R ldap:ldap slapd.d
    chmod -R 0750 slapd.d
    mv slapd.conf slapd.conf.bak
    cd $oldpath
    service ldap start
    sleep 3

#+end_src
#+begin_src sh :exports code :noweb yes
<<run-slapd-d>>
#+end_src

#+name: run-modify
#+begin_src sh :exports none
    ROOT_PWD=$(slappasswd -s $LDAP_ROOT_PASSWORD)
    # Use bash variable subsitution to escape special chars http://stackoverflow.com/a/14339705
    sed -i "s+%LDAP_ROOT_PASSWORD%+${ROOT_PWD//+/\\+}+" /root/manager.ldif
    ldapmodify -v -D cn=Manager,cn=config -f /root/manager.ldif -x -w 1

    MANAGER_PWD=$(slappasswd -s $LDAP_MANAGER_PASSWORD)
    sed -i "s+%LDAP_MANAGER_PASSWORD%+${MANAGER_PWD//+/\\+}+" /root/domain.ldif
    ldapmodify  -v -D cn=Manager,cn=config -f /root/domain.ldif -x -w $LDAP_ROOT_PASSWORD

    ldapadd -x -D cn=Manager,dc=tuleap,dc=local -w $LDAP_MANAGER_PASSWORD -f /root/base.ldif

#+end_src
#+begin_src sh :exports code :noweb yes
<<run-modify>>
#+end_src

#+name: run-postfix
#+begin_src sh :exports none
    # kill -INT `cat /var/run/openldap/slapd.pid`
    # service ldap stop
    killall slapd
    sleep 3

    mkdir /data/lib /data/etc
    cp -ar /var/lib/ldap /data/lib
    cp -ar /etc/openldap /data/etc
fi

rm -rf /var/lib/ldap && ln -s /data/lib/ldap /var/lib/ldap
rm -rf /etc/openldap && ln -s /data/etc/openldap /etc/openldap

exec /usr/sbin/slapd -h "ldap:/// ldaps:/// ldapi:///" -u ldap -d $DEBUG_LEVEL
#+end_src

#+begin_html
<br/><a href="javascript:toggleDiv('myContent-manager');" class="fa">manager.ldif</a>
#+end_html

#+HTML: <div id="myContent-manager" style="display:true">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-server/manager.ldif src ldif
#+HTML: </div>

#+begin_html
<br/><a href="javascript:toggleDiv('myContent-domain');" class="fa">domain.ldif</a>
#+end_html

#+HTML: <div id="myContent-domain" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-server/domain.ldif src ldif
#+HTML: </div>

#+begin_html
<br/><a href="javascript:toggleDiv('myContent-base');" class="fa">base.ldif</a>
#+end_html

#+HTML: <div id="myContent-base" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-server/base.ldif src ldif
#+HTML: </div>

#+begin_src sh :tangle ~/git/cc/cc-ldap-centos/ldap-server/run.sh :exports none :noweb yes
<<run-prefix>>
<<run-db-config>>
<<run-slapd-conf>>
<<run-slapd-d>>
<<run-modify>>
<<run-postfix>>
#+end_src

** OpenLDAP 2.4 и CentOS 6
:PROPERTIES:
:CUSTOM_ID: ldap2.4-centos6
:ID:       af4bb15a-67f0-4e1a-8ce6-18c118ff10cd
:END:

#+begin_html
<a href="javascript:toggleDiv('myContent2');" class="fa">slapd.conf.obsolete</a>
#+end_html

#+HTML: <div id="myContent2" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-server/slapd.conf.obsolete src conf-space
#+HTML: </div>


* Настройка аутентификации пользователей при помощи LDAP
:PROPERTIES:
:CUSTOM_ID: authentification
:ID:       49b5e2df-0c06-445a-ae9e-66bcd6cc9e40
:END:

#+begin_quote
Необходимо разработать документацию по настройке аутентификации пользователей при помощи LDAP в ОС CentOS 5. Проверить работоспособность выработанных инструкций в ОС CentOS 6.

В документацию должно входить:

- Список пакетов, которые необходимо установить;
- Список файлов, модификация которых необходима для настройки процесса аутентификации посредством LDAP;
- Описание всех опций, выставляемых в этих файлах.
#+end_quote

#+begin_html
<a href="javascript:toggleDiv('myContent-run');" class="fa">ldap-client/run.sh</a>
#+end_html

#+HTML: <div id="myContent-run" style="display:true">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-client/run.sh src sh
#+HTML: </div>

#+begin_html
<br/><a href="javascript:toggleDiv('myContent-client5');" class="fa">ldap-client/Dockerfile</a>
#+end_html

#+HTML: <div id="myContent-client5" style="display:true">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-client/Dockerfile src dockerfile :lines "7-8"
#+HTML: </div>

#+begin_html
<br/><a href="javascript:toggleDiv('myContent-client6');" class="fa">ldap-client/Dockerfile-centos6</a>
#+end_html

#+HTML: <div id="myContent-client6" style="display:true">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-client/Dockerfile-centos6 src dockerfile :lines "9-10"
#+HTML: </div>



* Схема БД LDAP
:PROPERTIES:
:CUSTOM_ID: schema
:ID:       b64d7c36-b2b3-49ac-9620-d7c94eb9ea31
:END:

#+begin_quote
Необходимо разработать схему БД LDAP, предназначенную для хранения учетных данных пользователей кластера.
#+end_quote

* Процесс добавления нового пользователя в систему
:PROPERTIES:
:CUSTOM_ID: new-user
:ID:       6fe3c37d-639a-4656-9675-bdc7a6c5ddb2
:END:

#+begin_quote
Необходимо разработать документацию по процессу добавления нового пользователя в систему, использующего аутентификацию посредством LDAP. Предложить CLI (или GUI WEB) интерфейс для выполнения данной операции. Ориентироваться на использование в ОС CentOS 5/6.
#+end_quote

* Перевести аутентификацию пользователей кластера на использование LDAP
:PROPERTIES:
:CUSTOM_ID: cluster
:ID:       db5bc4cf-74c3-40e0-b8b3-d57f3f32e338
:END:

