#+TITLE: Аутентификация пользователей CentOS 5/6 с использованием OpenLDAP 2.3/2.4
#+OPTIONS: toc:4 H:6 num:nil html-postamble:nil ^:nil tags:nil
#+SETUPFILE: theme-readtheorg-local.setup

* Установка и настройка сервера OpenLDAP
:PROPERTIES:
:CUSTOM_ID: install-and-config
:ID:       f3a148ae-26f4-4c54-a25c-532d2b9086ba
:END:

#+begin_quote
Необходимо разработать документацию по установке и настройке сервера LDAP в ОС CentOS 5. Предпочтение отдавать реализациям, доступным в базовом репозитории дистрибутива. Проверить работоспособность выработанных инструкций в ОС CentOS 6.
#+end_quote

# Процедура [[convert][конвертации]]

#+begin_sidebar
Команды и конфигурационные файлы прошли проверку на работоспособность в тестовом программном окружении, доступном в проекте [[https://github.com/boykov/cc-ldap-centos][cc-ldap-centos]].
#+end_sidebar

** Установка OpenLDAP
:PROPERTIES:
:CUSTOM_ID: install-openldap
:ID:       cdb77a09-a1eb-4db8-ad05-e45c3b49418c
:END:

# #+INCLUDE: "../ldap-server/Dockerfile" src dockerfile :lines "6-7"

Базовые репозитории дистрибутивов CentOS 5 и CentOS 6 содержат 2.3 и 2.4 версию OpenLDAP, соответственно. Выполнив стандартную установку
# #+INCLUDE: "../ldap-server/Dockerfile" src dockerfile :lines "18-21"
# #+begin_tip
# Там, где это не вызывает недоразумений, иногда будет использоваться синтаксис Dockerfile. Например, предыдущая команда означает просто src_sh[:exports code]{yum -y install openldap-server openldap-clients}.
# #+end_tip
#+begin_src sh
yum -y install openldap-servers openldap-clients sudo
#+end_src
получаем 2 конфигурации, различающиеся в некоторых деталях. Например, название сервиса: *ldap* в случае CentOS 5/2.3 OpenLDAP (5/2.3) и *slapd* в случае CentOS 6/2.4 OpenLDAP (6/2.4).

#+name: run-prefix
#+begin_src sh :exports none
#!/bin/bash

# for testing purpose
LDAP_ROOT_PASSWORD=root
LDAP_MANAGER_PASSWORD=manager

set -e

if [ ! -f /data/lib/ldap/DB_CONFIG ]; then
    if [ -z "$LDAP_ROOT_PASSWORD" -o -z "$LDAP_MANAGER_PASSWORD" ]; then
	echo "Need LDAP_ROOT_PASSWORD and LDAP_MANAGER_PASSWORD"
	exit
    fi

#+end_src

** Настройка базы данных BDB
:PROPERTIES:
:CUSTOM_ID: configure-bdb
:ID:       af4bb15a-67f0-4e1a-8ce6-18c118ff10cd
:END:

Для запуска сервиса *ldap* (*slapd*) необходимо подготовить каталог и файл конфигурации базы данных. Расположение образца файла настройки, в 5/2.3
#+name: run-db-config
#+begin_src sh :exports none
    cp /etc/openldap/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
    chown ldap. /var/lib/ldap/DB_CONFIG

#+end_src
#+begin_src sh :exports code :noweb yes
<<run-db-config>>
#+end_src
а в 6/2.4
#+name: run-db-config6
#+begin_src sh :exports none
    cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
    chown ldap. /var/lib/ldap/DB_CONFIG

#+end_src
#+begin_src sh :exports code :noweb yes
<<run-db-config6>>
#+end_src
Используем настройки без изменений в обеих конфигурациях.
** Предварительная настройка схемы БД LDAP
:PROPERTIES:
:CUSTOM_ID: configure-slapd
:ID:       fd3e3e26-d416-4cc5-9dfa-554caeaf7830
:END:

Конфигурация 5/2.3 по умолчанию настраивается файлом *slapd.conf*. Такой подход считается устаревшим, [[http://www.openldap.org/doc/admin24/guide.html#Converting%20old%20style%20{{slapd.conf}}%285%29%20file%20to%20{{cn=config}}%20format][рекомендуется]] использовать *cn=config* формат. Конфигурация 6/2.4 поставляется с двумя эквивалентными вариантами, доступными через файл *slapd.conf.obsolete* и *slapd.d* каталог, содержащий настройки в *cn=config* формате.

Внесем небольшие изменения в конфигурационный файл для 5/2.3
#+begin_html
<a href="javascript:toggleDiv('myContent');" class="fa">/root/slapd.conf</a>
#+end_html

#+HTML: <div id="myContent" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-server/slapd.conf src conf-space
#+HTML: </div>
#+INCLUDE: ../gen/slapd.diff src diff
и произведем первый запуск сервиса
#+name: run-slapd-conf
#+begin_src sh :exports none
    cp /usr/share/doc/sudo-1.7.2p1/schema.OpenLDAP /etc/openldap/schema/sudo.schema
    chown ldap. /etc/openldap/schema/sudo.schema

    rm -f /etc/openldap/slapd.conf
    cp /root/slapd.conf /etc/openldap/slapd.conf
    chown ldap. /etc/openldap/slapd.conf

#+end_src
#+begin_src sh :exports code :noweb yes
<<run-slapd-conf>>
<<run-slapd-start>>
#+end_src

#+name: run-slapd-start
#+begin_src sh :exports none
    service ldap start
#+end_src

#+name: run-slapd-start6
#+begin_src sh :exports none
    service slapd start
#+end_src
Выполним аналогичные действия для 6/2.4
#+begin_html
<a href="javascript:toggleDiv('myContent2');" class="fa">/root/slapd.conf.obsolete</a>
#+end_html

#+HTML: <div id="myContent2" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-server/slapd.conf.obsolete src conf-space
#+HTML: </div>
#+INCLUDE: ../gen/slapd.obsolete.diff src diff

#+begin_attention
В случае с CentOS 6 и OpenLDAP 2.4 здесь дополнительно удаляется конфигурация *slapd.d*.
#+end_attention

#+name: run-slapd-conf6
#+begin_src sh :exports none
    cp /usr/share/doc/sudo-1.8.6p3/schema.OpenLDAP /etc/openldap/schema/sudo.schema
    chown ldap. /etc/openldap/schema/sudo.schema

    rm -f /etc/openldap/slapd.conf
    cp /root/slapd.conf.obsolete /etc/openldap/slapd.conf
    chown ldap. /etc/openldap/slapd.conf
    rm -rf /etc/openldap/slapd.d

#+end_src
#+begin_src sh :exports code :noweb yes
<<run-slapd-conf6>>
<<run-slapd-start6>>
#+end_src

<<convert>>Теперь для обеих конфигураций можно осуществить переход к *cn=config* формату и избавиться от *slapd.conf*
#+name: run-slapd-d
#+begin_src sh :exports none
    sleep 3

    killall slapd
    oldpath=`pwd`
    cd /etc/openldap
    mkdir slapd.d
    slaptest -f slapd.conf -F slapd.d
    chown -R ldap:ldap slapd.d
    chmod -R 0750 slapd.d
    mv slapd.conf slapd.conf.bak
    cd $oldpath
#+end_src
#+begin_src sh :exports code :noweb yes
<<run-slapd-d>>
#+end_src
После перезапуска, для 5/2.3
#+begin_src sh :exports code :noweb yes
<<run-slapd-start>>
#+end_src
и для 6/2.4
#+begin_src sh :exports code :noweb yes
<<run-slapd-start6>>
#+end_src
получаем сервисы, отличающиеся только настройками по умолчанию, поставляемыми из базовых репозиториев в файлах */etc/openldap/slapd.conf* (5/2.3) и */usr/share/openldap-servers/slapd.conf.obsolete* (6/2.4).

** Подготовка к тестированию аутентификации при помощи LDAP
:PROPERTIES:
:CUSTOM_ID: add-manager
:ID:       17e9c727-04eb-495e-97a8-36ab4f2b3cc9
:END:

Чтобы получить минимально работоспособный сервер LDAP, позволяющий осуществлять аутентификацию для клиентских систем, внесем необходимые изменения в схему. В частности, сконфигурируем базу *bdb* для доменного имени *dc=mercury,dc=febras,dc=net*, пропишем пароли для менеджеров схемы *cn=Manager,cn=config* и *cn=Manager,dc=mercury,dc=febras,dc=net*, добавим 2 подразделения *groups* и *people*. Также, для примера, пропишем в *domain.ldif* два правила доступа --- в дальнейшем, при [[id:b64d7c36-b2b3-49ac-9620-d7c94eb9ea31][настройке схемы БД LDAP]], потребуется переконфигурировать все правила доступа заново.

Для обеих конфигураций выполним следующие действия

#+name: run-modify
#+begin_src sh :exports none
    sleep 3

    ROOT_PWD=$(slappasswd -s $LDAP_ROOT_PASSWORD)
    # Use bash variable subsitution to escape special chars http://stackoverflow.com/a/14339705
    sed -i "s+%LDAP_ROOT_PASSWORD%+${ROOT_PWD//+/\\+}+" /root/manager.ldif
    ldapmodify -v -D cn=Manager,cn=config -f /root/manager.ldif -x -w 1

    MANAGER_PWD=$(slappasswd -s $LDAP_MANAGER_PASSWORD)
    sed -i "s+%LDAP_MANAGER_PASSWORD%+${MANAGER_PWD//+/\\+}+" /root/domain.ldif
    ldapmodify  -v -D cn=Manager,cn=config -f /root/domain.ldif -x -w $LDAP_ROOT_PASSWORD

    ldapadd -x -D cn=Manager,dc=mercury,dc=febras,dc=net -w $LDAP_MANAGER_PASSWORD -f /root/base.ldif
    ldapadd -x -D cn=Manager,dc=mercury,dc=febras,dc=net -w $LDAP_MANAGER_PASSWORD -f /root/admin.ldif

#+end_src
#+begin_src sh :exports code :noweb yes
<<run-modify>>
#+end_src

#+name: run-postfix
#+begin_src sh :exports none
    killall slapd
    sleep 3

    mkdir /data/lib /data/etc
    cp -ar /var/lib/ldap /data/lib
    cp -ar /etc/openldap /data/etc
fi

rm -rf /var/lib/ldap && ln -s /data/lib/ldap /var/lib/ldap
rm -rf /etc/openldap && ln -s /data/etc/openldap /etc/openldap

exec /usr/sbin/slapd -h "ldap:/// ldaps:/// ldapi:///" -u ldap -d $DEBUG_LEVEL
#+end_src

#+begin_html
<br/><a href="javascript:toggleDiv('myContent-manager');" class="fa">/root/manager.ldif</a>
#+end_html
#+HTML: <div id="myContent-manager" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-server/manager.ldif src ldif
#+HTML: </div>
#+begin_html
<br/><a href="javascript:toggleDiv('myContent-domain');" class="fa">/root/domain.ldif</a>
#+end_html
#+HTML: <div id="myContent-domain" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-server/domain.ldif src ldif
#+HTML: </div>
#+begin_html
<br/><a href="javascript:toggleDiv('myContent-base');" class="fa">/root/base.ldif</a>
#+end_html
#+HTML: <div id="myContent-base" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-server/base.ldif src ldif
#+HTML: </div>
#+begin_html
<br/><a href="javascript:toggleDiv('myContent-admin');" class="fa">/root/admin.ldif</a>
#+end_html
#+HTML: <div id="myContent-admin" style="display:true">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-server/admin.ldif src ldif
#+HTML: </div>

#+begin_src sh :tangle ~/git/cc/cc-ldap-centos/ldap-server/run.sh :exports none :noweb yes
<<run-prefix>>
<<run-db-config>>
<<run-slapd-conf>>
<<run-slapd-start>>
<<run-slapd-d>>
<<run-slapd-start>>
<<run-modify>>
<<run-postfix>>
#+end_src

#+begin_src sh :tangle ~/git/cc/cc-ldap-centos/ldap-server/run6.sh :exports none :noweb yes
<<run-prefix>>
<<run-db-config6>>
<<run-slapd-conf6>>
<<run-slapd-start6>>
<<run-slapd-d>>
<<run-slapd-start6>>
<<run-modify>>
<<run-postfix>>
#+end_src

Для тестирования аутентификации будем использовать запись *username*.

* Настройка аутентификации пользователей при помощи LDAP
:PROPERTIES:
:CUSTOM_ID: authentification
:ID:       49b5e2df-0c06-445a-ae9e-66bcd6cc9e40
:END:

#+begin_quote
Необходимо разработать документацию по настройке аутентификации пользователей при помощи LDAP в ОС CentOS 5. Проверить работоспособность выработанных инструкций в ОС CentOS 6.

В документацию должно входить:

- Список пакетов, которые необходимо установить;
- Список файлов, модификация которых необходима для настройки процесса аутентификации посредством LDAP;
- Описание всех опций, выставляемых в этих файлах.
#+end_quote

#+begin_src sh :exports code
yum install -y openssh-server openldap-clients nss_ldap authconfig
yum install -y openldap-servers sudo
#+end_src

#+begin_src sh :exports code
yum install -y openssh-server openldap-clients nss-pam-ldapd authconfig
RUN yum install -y migrationtools sudo
#+end_src

#+begin_html
<a href="javascript:toggleDiv('myContent-run');" class="fa">/root/run.sh</a>
#+end_html

#+HTML: <div id="myContent-run" style="display:true">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/ldap-client/run.sh src sh
#+HTML: </div>

#+begin_src conf-colon
username:x:1050:1030:User Name:/home/webminder:/bin/bash
#+end_src

#+begin_html
<a href="javascript:toggleDiv('myContent-client');" class="fa">client.diff</a>
#+end_html

#+HTML: <div id="myContent-client" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/gen/client.diff src diff
#+HTML: </div>

#+begin_html
<br/><a href="javascript:toggleDiv('myContent-client6');" class="fa">client6.diff</a>
#+end_html

#+HTML: <div id="myContent-client6" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/gen/client6.diff src diff
#+HTML: </div>

* Схема БД LDAP
:PROPERTIES:
:CUSTOM_ID: schema
:ID:       b64d7c36-b2b3-49ac-9620-d7c94eb9ea31
:END:

#+begin_quote
Необходимо разработать схему БД LDAP, предназначенную для хранения учетных данных пользователей кластера.
#+end_quote

#+begin_html
<a href="javascript:toggleDiv('myContent-passwd');" class="fa">passwd.ldif</a>
#+end_html

#+HTML: <div id="myContent-passwd" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/gen/passwd.ldif src ldif
#+HTML: </div>

# do not need migrate centos 6 users
# #+begin_html
# <br/><a href="javascript:toggleDiv('myContent-passwd6');" class="fa">passwd6.ldif</a>
# #+end_html

# #+HTML: <div id="myContent-passwd6" style="display:none">
# #+INCLUDE: /home/eab/git/cc/cc-ldap-centos/gen/passwd6.ldif src ldif
# #+HTML: </div>


#+begin_html
<br/><a href="javascript:toggleDiv('myContent-group');" class="fa">group.ldif</a>
#+end_html

#+HTML: <div id="myContent-group" style="display:none">
#+INCLUDE: /home/eab/git/cc/cc-ldap-centos/gen/group.ldif src ldif
#+HTML: </div>

# do not need migrate centos 6 users
# #+begin_html
# <br/><a href="javascript:toggleDiv('myContent-group6');" class="fa">group6.ldif</a>
# #+end_html

# #+HTML: <div id="myContent-group6" style="display:none">
# #+INCLUDE: /home/eab/git/cc/cc-ldap-centos/gen/group6.ldif src ldif
# #+HTML: </div>


* Процесс добавления нового пользователя в систему
:PROPERTIES:
:CUSTOM_ID: new-user
:ID:       6fe3c37d-639a-4656-9675-bdc7a6c5ddb2
:END:

#+begin_quote
Необходимо разработать документацию по процессу добавления нового пользователя в систему, использующего аутентификацию посредством LDAP. Предложить CLI (или GUI WEB) интерфейс для выполнения данной операции. Ориентироваться на использование в ОС CentOS 5/6.
#+end_quote

* Перевести аутентификацию пользователей кластера на использование LDAP
:PROPERTIES:
:CUSTOM_ID: cluster
:ID:       db5bc4cf-74c3-40e0-b8b3-d57f3f32e338
:END:

