#+TITLE: Аутентификация пользователей CentOS 5/6 с использованием OpenLDAP 2.3/2.4
#+OPTIONS: toc:4 H:6 num:nil html-postamble:nil ^:nil tags:nil
#+SETUPFILE: theme-readtheorg-local.setup

Конфигурационные файлы: https://github.com/boykov/cc-ldap-centos

* Установка и настройка сервера OpenLDAP
:PROPERTIES:
:ID:       f3a148ae-26f4-4c54-a25c-532d2b9086ba
:END:

#+begin_quote
Необходимо разработать документацию по установке и настройке сервера LDAP в ОС CentOS 5. Предпочтение отдавать реализациям, доступным в базовом репозитории дистрибутива. Проверить работоспособность выработанных инструкций в ОС CentOS 6.
#+end_quote

** OpenLDAP 2.3 и CentOS 5

#+INCLUDE: "/home/eab/data/gitno/github/docker-ldap/Dockerfile" src dockerfile :lines "17-20"

** OpenLDAP 2.4 и CentOS 6


* Настройка аутентификации пользователей при помощи LDAP
:PROPERTIES:
:ID:       49b5e2df-0c06-445a-ae9e-66bcd6cc9e40
:END:

#+begin_quote
Необходимо разработать документацию по настройке аутентификации пользователей при помощи LDAP в ОС CentOS 5. Проверить работоспособность выработанных инструкций в ОС CentOS 6.

В документацию должно входить:

- Список пакетов, которые необходимо установить;
- Список файлов, модификация которых необходима для настройки процесса аутентификации посредством LDAP;
- Описание всех опций, выставляемых в этих файлах.
#+end_quote

* Разработать схему БД LDAP
:PROPERTIES:
:ID:       b64d7c36-b2b3-49ac-9620-d7c94eb9ea31
:END:

Необходимо разработать схему БД LDAP, предназначенную для хранения учетных данных пользователей кластера.

* Разработать документацию по процессу добавления нового пользователя в систему
:PROPERTIES:
:ID:       6fe3c37d-639a-4656-9675-bdc7a6c5ddb2
:END:

Необходимо разработать документацию по процессу добавления нового пользователя в систему, использующего аутентификацию посредством LDAP. Предложить CLI (или GUI WEB) интерфейс для выполнения данной операции. Ориентироваться на использование в ОС CentOS 5/6.

* Перевести аутентификацию пользователей кластера на использование LDAP
:PROPERTIES:
:ID:       db5bc4cf-74c3-40e0-b8b3-d57f3f32e338
:END:

